# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_project/TJU-2025-Autumn-Digital-Design-and-Computer-Architecture/CPU/Mcpu/Loongarch32_Lite.srcs/sources_1/ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_project/TJU-2025-Autumn-Digital-Design-and-Computer-Architecture/CPU/Mcpu/Loongarch32_Lite.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/vivado_project/TJU-2025-Autumn-Digital-Design-and-Computer-Architecture/CPU/Mcpu/Loongarch32_Lite.srcs/sources_1/ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_project/TJU-2025-Autumn-Digital-Design-and-Computer-Architecture/CPU/Mcpu/Loongarch32_Lite.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
