# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
# IP: The module: 'design_1_cg_fpga_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xbar_0/cg_fpga_full_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xbar_0 || ORIG_REF_NAME==cg_fpga_full_xbar_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_axi_vdma_0_0/cg_fpga_full_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_full_axi_vdma_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_intc_0_0/cg_fpga_full_cg_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_intc_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_uartlite_0_0/cg_fpga_full_cg_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_uartlite_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i1_0/cg_fpga_full_cg_fpga_axi_gpio_i1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i2_0/cg_fpga_full_cg_fpga_axi_gpio_i2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i2_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o1_0/cg_fpga_full_cg_fpga_axi_gpio_o1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o2_0/cg_fpga_full_cg_fpga_axi_gpio_o2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o2_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_processing_system7_0_0/cg_fpga_full_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_processing_system7_0_0 || ORIG_REF_NAME==cg_fpga_full_processing_system7_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xbar_1/cg_fpga_full_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xbar_1 || ORIG_REF_NAME==cg_fpga_full_xbar_1} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_rst_ps7_0_100M_0/cg_fpga_full_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_rst_ps7_0_100M_0 || ORIG_REF_NAME==cg_fpga_full_rst_ps7_0_100M_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_util_vector_logic_0_0/cg_fpga_full_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_util_vector_logic_0_0 || ORIG_REF_NAME==cg_fpga_full_util_vector_logic_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_v_vid_in_axi4s_0_0/cg_fpga_full_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cg_fpga_full_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconcat_0_0/cg_fpga_full_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconcat_0_0 || ORIG_REF_NAME==cg_fpga_full_xlconcat_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconcat_1_0/cg_fpga_full_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconcat_1_0 || ORIG_REF_NAME==cg_fpga_full_xlconcat_1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconcat_2_0/cg_fpga_full_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconcat_2_0 || ORIG_REF_NAME==cg_fpga_full_xlconcat_2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconcat_3_0/cg_fpga_full_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconcat_3_0 || ORIG_REF_NAME==cg_fpga_full_xlconcat_3_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconstant_0_0/cg_fpga_full_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconstant_0_0 || ORIG_REF_NAME==cg_fpga_full_xlconstant_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconstant_1_0/cg_fpga_full_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconstant_1_0 || ORIG_REF_NAME==cg_fpga_full_xlconstant_1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconstant_2_0/cg_fpga_full_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconstant_2_0 || ORIG_REF_NAME==cg_fpga_full_xlconstant_2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlslice_0_0/cg_fpga_full_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlslice_0_0 || ORIG_REF_NAME==cg_fpga_full_xlslice_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlslice_1_0/cg_fpga_full_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlslice_1_0 || ORIG_REF_NAME==cg_fpga_full_xlslice_1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlslice_2_0/cg_fpga_full_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlslice_2_0 || ORIG_REF_NAME==cg_fpga_full_xlslice_2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_auto_pc_0/cg_fpga_full_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_auto_pc_0 || ORIG_REF_NAME==cg_fpga_full_auto_pc_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_auto_pc_1/cg_fpga_full_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_auto_pc_1 || ORIG_REF_NAME==cg_fpga_full_auto_pc_1} -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cg_fpga_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_axi_vdma_0_0/cg_fpga_full_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_full_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_axi_vdma_0_0/cg_fpga_full_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_full_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_axi_vdma_0_0/cg_fpga_full_axi_vdma_0_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_intc_0_0/cg_fpga_full_cg_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_intc_0_0/cg_fpga_full_cg_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_intc_0_0/cg_fpga_full_cg_axi_intc_0_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_uartlite_0_0/cg_fpga_full_cg_axi_uartlite_0_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_uartlite_0_0/cg_fpga_full_cg_axi_uartlite_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i1_0/cg_fpga_full_cg_fpga_axi_gpio_i1_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i1_0/cg_fpga_full_cg_fpga_axi_gpio_i1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i2_0/cg_fpga_full_cg_fpga_axi_gpio_i2_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i2_0/cg_fpga_full_cg_fpga_axi_gpio_i2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i2_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o1_0/cg_fpga_full_cg_fpga_axi_gpio_o1_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o1_0/cg_fpga_full_cg_fpga_axi_gpio_o1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o2_0/cg_fpga_full_cg_fpga_axi_gpio_o2_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o2_0/cg_fpga_full_cg_fpga_axi_gpio_o2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o2_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_processing_system7_0_0/cg_fpga_full_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_processing_system7_0_0 || ORIG_REF_NAME==cg_fpga_full_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_rst_ps7_0_100M_0/cg_fpga_full_rst_ps7_0_100M_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_rst_ps7_0_100M_0 || ORIG_REF_NAME==cg_fpga_full_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_v_vid_in_axi4s_0_0/cg_fpga_full_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cg_fpga_full_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_auto_pc_0/cg_fpga_full_auto_pc_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_auto_pc_1/cg_fpga_full_auto_pc_1_ooc.xdc

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
# IP: The module: 'design_1_cg_fpga_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xbar_0/cg_fpga_full_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xbar_0 || ORIG_REF_NAME==cg_fpga_full_xbar_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_axi_vdma_0_0/cg_fpga_full_axi_vdma_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_full_axi_vdma_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_intc_0_0/cg_fpga_full_cg_axi_intc_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_intc_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_uartlite_0_0/cg_fpga_full_cg_axi_uartlite_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_uartlite_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i1_0/cg_fpga_full_cg_fpga_axi_gpio_i1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i2_0/cg_fpga_full_cg_fpga_axi_gpio_i2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i2_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o1_0/cg_fpga_full_cg_fpga_axi_gpio_o1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o2_0/cg_fpga_full_cg_fpga_axi_gpio_o2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o2_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_processing_system7_0_0/cg_fpga_full_processing_system7_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_processing_system7_0_0 || ORIG_REF_NAME==cg_fpga_full_processing_system7_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xbar_1/cg_fpga_full_xbar_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xbar_1 || ORIG_REF_NAME==cg_fpga_full_xbar_1} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_rst_ps7_0_100M_0/cg_fpga_full_rst_ps7_0_100M_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_rst_ps7_0_100M_0 || ORIG_REF_NAME==cg_fpga_full_rst_ps7_0_100M_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_util_vector_logic_0_0/cg_fpga_full_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_util_vector_logic_0_0 || ORIG_REF_NAME==cg_fpga_full_util_vector_logic_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_v_vid_in_axi4s_0_0/cg_fpga_full_v_vid_in_axi4s_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cg_fpga_full_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconcat_0_0/cg_fpga_full_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconcat_0_0 || ORIG_REF_NAME==cg_fpga_full_xlconcat_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconcat_1_0/cg_fpga_full_xlconcat_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconcat_1_0 || ORIG_REF_NAME==cg_fpga_full_xlconcat_1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconcat_2_0/cg_fpga_full_xlconcat_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconcat_2_0 || ORIG_REF_NAME==cg_fpga_full_xlconcat_2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconcat_3_0/cg_fpga_full_xlconcat_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconcat_3_0 || ORIG_REF_NAME==cg_fpga_full_xlconcat_3_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconstant_0_0/cg_fpga_full_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconstant_0_0 || ORIG_REF_NAME==cg_fpga_full_xlconstant_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconstant_1_0/cg_fpga_full_xlconstant_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconstant_1_0 || ORIG_REF_NAME==cg_fpga_full_xlconstant_1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlconstant_2_0/cg_fpga_full_xlconstant_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlconstant_2_0 || ORIG_REF_NAME==cg_fpga_full_xlconstant_2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlslice_0_0/cg_fpga_full_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlslice_0_0 || ORIG_REF_NAME==cg_fpga_full_xlslice_0_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlslice_1_0/cg_fpga_full_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlslice_1_0 || ORIG_REF_NAME==cg_fpga_full_xlslice_1_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_xlslice_2_0/cg_fpga_full_xlslice_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_xlslice_2_0 || ORIG_REF_NAME==cg_fpga_full_xlslice_2_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_auto_pc_0/cg_fpga_full_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_auto_pc_0 || ORIG_REF_NAME==cg_fpga_full_auto_pc_0} -quiet] -quiet

# IP: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_auto_pc_1/cg_fpga_full_auto_pc_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cg_fpga_full_auto_pc_1 || ORIG_REF_NAME==cg_fpga_full_auto_pc_1} -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cg_fpga_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_axi_vdma_0_0/cg_fpga_full_axi_vdma_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_full_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_axi_vdma_0_0/cg_fpga_full_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_full_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_axi_vdma_0_0/cg_fpga_full_axi_vdma_0_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_intc_0_0/cg_fpga_full_cg_axi_intc_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_intc_0_0/cg_fpga_full_cg_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_intc_0_0/cg_fpga_full_cg_axi_intc_0_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_uartlite_0_0/cg_fpga_full_cg_axi_uartlite_0_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_axi_uartlite_0_0/cg_fpga_full_cg_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_full_cg_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i1_0/cg_fpga_full_cg_fpga_axi_gpio_i1_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i1_0/cg_fpga_full_cg_fpga_axi_gpio_i1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i2_0/cg_fpga_full_cg_fpga_axi_gpio_i2_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_i2_0/cg_fpga_full_cg_fpga_axi_gpio_i2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i2_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_i2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o1_0/cg_fpga_full_cg_fpga_axi_gpio_o1_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o1_0/cg_fpga_full_cg_fpga_axi_gpio_o1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o2_0/cg_fpga_full_cg_fpga_axi_gpio_o2_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_cg_fpga_axi_gpio_o2_0/cg_fpga_full_cg_fpga_axi_gpio_o2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o2_0 || ORIG_REF_NAME==cg_fpga_full_cg_fpga_axi_gpio_o2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_processing_system7_0_0/cg_fpga_full_processing_system7_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_processing_system7_0_0 || ORIG_REF_NAME==cg_fpga_full_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_rst_ps7_0_100M_0/cg_fpga_full_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_rst_ps7_0_100M_0 || ORIG_REF_NAME==cg_fpga_full_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_v_vid_in_axi4s_0_0/cg_fpga_full_v_vid_in_axi4s_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_full_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cg_fpga_full_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_auto_pc_0/cg_fpga_full_auto_pc_0_ooc.xdc

# XDC: d:/vivado_project/TJU-2025/SOC/Loongarch32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_cg_fpga_0_0/src/cg_fpga_full_auto_pc_1/cg_fpga_full_auto_pc_1_ooc.xdc
