webtalk_init -webtalk_dir D:/vivado_project/TJU-2025/CPU/Mcpu/Loongarch32_Lite.sim/sim_1/behav/xsim/xsim.dir/tb_Loongarch32_Lite_FullSyS_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan 13 12:26:03 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3b8bbfff-1ebe-45cf-95d1-2c58edec1709" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "329b56de6c334595be6a7c2f359d0bf7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "86" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-13500HX" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2535717146 -regid "" -xml D:/vivado_project/TJU-2025/CPU/Mcpu/Loongarch32_Lite.sim/sim_1/behav/xsim/xsim.dir/tb_Loongarch32_Lite_FullSyS_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/vivado_project/TJU-2025/CPU/Mcpu/Loongarch32_Lite.sim/sim_1/behav/xsim/xsim.dir/tb_Loongarch32_Lite_FullSyS_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/vivado_project/TJU-2025/CPU/Mcpu/Loongarch32_Lite.sim/sim_1/behav/xsim/xsim.dir/tb_Loongarch32_Lite_FullSyS_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
